language: node_js

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
              g++-6

env:
    - CC="gcc" CXX="g++"

install:
    - npm install
script:
    - node clubru.js -tl
    - node clubru.js -ei
    - node clubru.js -e
